// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KlaB8cd1Io2hcwCVLWuZA99zGdynL-s',
    appId: '1:1056242531913:web:87006ad9ec1728a532c998',
    messagingSenderId: '1056242531913',
    projectId: 'value-incrimenting',
    authDomain: 'value-incrimenting.firebaseapp.com',
    storageBucket: 'value-incrimenting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0x6WBW7AB6lue2gQL7-7-5vvUvt8cTDI',
    appId: '1:1056242531913:android:7c8d0d841bec765732c998',
    messagingSenderId: '1056242531913',
    projectId: 'value-incrimenting',
    storageBucket: 'value-incrimenting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqW_C5cUK-9MYKem5sDw2gZnIVv049fPg',
    appId: '1:1056242531913:ios:fd0496c1dae30e9732c998',
    messagingSenderId: '1056242531913',
    projectId: 'value-incrimenting',
    storageBucket: 'value-incrimenting.appspot.com',
    iosBundleId: 'com.example.valueIncriment',
  );
}
